title: 'M-Akc Website'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/"
url: "https://m-akc.github.io"

header_pages:
  - index.md
  - peter.md
  - services.md
  - about.md

style: light 

footer: 'Contact me: <a href="https://t.me/m_akc">Telegram</a>'

# Build settings
#markdown: kramdown
theme: m-akc.github.io
